// In-memory subset of public/vikings.json, with image paths
// rewritten to the project's copied PNGs.
window.VIKINGS = [
  { id: 'longship',         name: 'Longship',                 oldNorse: 'Langskip',     image: '../../public/images/sea-stuff/longboat.png',                category: 'ship',     description: "A long, narrow warship built for speed under both oar and sail. The shallow draft let viking crews land on beaches and travel up rivers other vessels couldn't reach." },
  { id: 'dragon-head-prow', name: 'Carved Dragon-Head Prow',  oldNorse: 'Drekahǫfuð',   image: '../../public/images/sea-stuff/carved-dragon-head-prow.png', category: 'ship',     description: "An ornately carved dragon or serpent head mounted on a longship's prow. Meant to frighten enemies and ward off hostile spirits." },
  { id: 'sun-compass',      name: 'Sun Compass',              oldNorse: 'Sólarsteinn',  image: '../../public/images/sea-stuff/sun-compass.png',             category: 'ship',     description: "A wooden disc with a central gnomon used to find true north by the shadow it cast." },
  { id: 'ulfberht',         name: 'Ulfberht Sword',           oldNorse: 'Ulfberht-sverð', image: '../../public/images/weapons/ulfberht-sword.png',          category: 'weapon',   description: "A high-carbon crucible-steel sword forged in the Rhineland, prized far above local ironwork. The +VLFBERHT+ inlay marked an early luxury brand." },
  { id: 'dane-axe',         name: 'Dane Axe',                 oldNorse: 'Breiðøx',      image: '../../public/images/weapons/dane-axe.png',                  category: 'weapon',   description: "A two-handed long-hafted axe with a broad, thin blade. Devastating against shield walls and the signature weapon of viking huscarls." },
  { id: 'round-shield',     name: 'Round Shield',             oldNorse: 'Skjǫldr',      image: '../../public/images/weapons/round-sheild.png',              category: 'armor',    description: "A round plank shield with an iron boss covering the central handgrip." },
  { id: 'spangenhelm',      name: 'Spangenhelm',              oldNorse: 'Spangahjálmr', image: '../../public/images/weapons/spangenhelm.png',               category: 'armor',    description: "A conical iron helmet built from riveted plates, often with a nasal guard. Despite popular myth, viking helmets had no horns." },
  { id: 'drinking-horn',    name: 'Drinking Horn',            oldNorse: 'Drykkjarhorn', image: '../../public/images/domstic-stuff/drinking-horn.png',       category: 'domestic', description: "A polished cattle or aurochs horn used for ale, mead, and ceremonial toasts." },
  { id: 'hnefatafl-board',  name: 'Hnefatafl Board',          oldNorse: 'Hnefatafl',    image: '../../public/images/domstic-stuff/hnefatafl-board.png',     category: 'domestic', description: "A strategy board game of unequal sides: a king and his defenders trying to escape a larger surrounding force." },
  { id: 'thors-hammer',     name: "Thor's Hammer Pendant",    oldNorse: 'Mjǫllnir',     image: '../../public/images/clothing/thors-hammer-pendant.png',     category: 'clothing', description: "A small silver or iron pendant shaped like the hammer of Thor. Worn for protection." },
  { id: 'cloak-brooch',     name: 'Cloak Brooch',             oldNorse: 'Sylgja',       image: '../../public/images/clothing/cloak-brooch.png',             category: 'clothing', description: "A penannular or ring brooch used to pin a heavy wool cloak at the shoulder." },
  { id: 'bone-comb',        name: 'Bone Comb',                oldNorse: 'Kambr',        image: '../../public/images/clothing/bone-comb.png',                category: 'clothing', description: "A double-sided comb made from riveted antler plates. Combs were a near-universal personal item." },
];
